alias lc="less -r"
alias h="history"
alias j="jobs"
alias la="ls -al"
alias lah="ls -hal"
alias laht="ls -halrt"
alias lessc="less -r"
alias lrt="ls -lrt"
alias cpg="rsync --partial --progress --append --rsh=ssh -r -h"
alias mvg="rsync --partial --progress --append --rsh=ssh -r -h --remove-sent-files"
alias pipenv3=python3.9 -m pipenv
