#!/usr/bin/env bash
#==============================================================================
# add to crontab like this:
# @reboot /bin/sleep 300; $HOME/bin/monodrive >/var/tmp/monodrive.log 2>&1
#==============================================================================
# Imports
#==============================================================================
. $HOME/.bash_envars
[ $? -ne 0 ] && exit 41
. $HOME/.bash_functions
[ $? -ne 0 ] && exit 42
#==============================================================================
# Constants
#==============================================================================
PGREP="/bin/grep -P"
MONITOR_WAIT_S=60
WAIT_FOR_AGENT_S=$ODRIVE_AGENT_WAIT_S
AGENT_ERROR="(There was an error sending the command, please make sure odrive agent or desktop is running.|You must have odrive agent or desktop running before using this script.)"
#==============================================================================
# Functions
#==============================================================================
function latest_sync_log
{
    echo "$(ls -1rt $ODRIVE_LOG.* 2>&1 | tail -n1)"
}
#==============================================================================
function agent_is_running
{
    $PGREP "$AGENT_ERROR" $(latest_sync_log) >/dev/null 2>&1
    return $((! $?))
}
#==============================================================================
function start_agent
{
    nohup $HOME/bin/odrive_agent &
}
#==============================================================================
function start_sync
{
    nohup $HOME/bin/odrive_sync --start &
}
#==============================================================================
# MAIN
#==============================================================================

kill_other_instances "$(basename "$0")"

agent_off_counter=0
is_running=false

info "monitoring started..."
while true; do
    if agent_is_running; then
        if ! $is_running; then
            info "the odrive agent is running"
            is_running=true
        else
            sleep $MONITOR_WAIT_S
        fi
    else
        is_running=false
        ((agent_off_counter += 1))
        warn "the odrive agent is not responding (down times: $agent_off_counter)"
        info "starting the odrive agent..."
        start_agent
        info "waiting ${WAIT_FOR_AGENT_S}s for the agent to get ready..."
        sleep $WAIT_FOR_AGENT_S
        info "starting a sync..."
        start_sync
        sleep $MONITOR_WAIT_S
    fi
done
