#!/usr/bin/env bash
. $HOME/bin/odrive_common

log_file=$(unique_log_filename)

# purge old log files
find $ODRIVE_LOG* -mtime +7 -type f -delete

# sync
python -u $ODRIVE sync $ODRIVE_AMAZON_PLACEHOLDER --recursive >>$log_file 2>&1

